apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service  # 使用动态名称
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}  # NodePort 设置
  selector:
    app: {{ .Release.Name }}  # 动态设置

