{{- if .Values.storage.usePersistentStorage }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}  # 使用 Helm release 名称动态生成
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}  # 使用 Helm release 名称动态生成
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}  # 使用 Helm release 名称动态生成
    spec:
      containers:
        - name: {{ .Release.Name }}-desktop  # 使用 Helm release 名称动态生成容器名称
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6901
          env:
            - name: VNC_PW
              value: {{ .Values.env.VNC_PW }}
          volumeMounts:
            - name: kasm-data
              mountPath: /home/kasm-user/shares
      volumes:
        - name: kasm-data
          {{- if eq .Values.storage.type "hostpath" }}
          hostPath:
            path: {{ .Values.storage.path }}
            type: DirectoryOrCreate
          {{- else if eq .Values.storage.type "StorageClass" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc  # 使用 Helm release 名称动态生成 PVC 名称
            storageClassName: {{ .Values.pvc.storageClassName | default "standard" }}
          {{- end }}
{{- else }}  # Add this section for Deployment if not using persistent storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}  # 使用 Helm release 名称动态生成
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}  # 使用 Helm release 名称动态生成
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}  # 使用 Helm release 名称动态生成
    spec:
      containers:
        - name: {{ .Release.Name }}-desktop  # 使用 Helm release 名称动态生成容器名称
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6901
          env:
            - name: VNC_PW
              value: {{ .Values.env.VNC_PW }}
{{- end }}  # Correctly close the else block

